### ISSUE TITLE
Feature request: Modify Extension feature to Transaction

### ISSUE THREAD

**Issue by nhpquy** [beowulf-foundation/beowulf-java#7]
**Create 2 additional type of Extension for Object FutureExtensions.**
- Void type and Json type.

**Solution:**
- Create new order id for each type of Extension.
- Create new class of each Extension (VoidExtension & JsonExtension) extends from Object FutureExtensions 
- Serialize Json format and Byte format for JsonExtension.

**Additional method:**
- Sign and broadcast transaction with Extensions.

**Comment by trongcauhcmus** [comment]
@congnghia0609 request accepted.
Please create new branch `feature_request` for @nhpquy

**Comment by trongcauhcmus** [comment]
this issue was link to 8241225ff1b7c86357a1ea2d32d82859c5d1d745
